###
GET http://localhost:1080
###
PUT http://localhost:1080

###
GET http://localhost:1080/foo

###
POST http://localhost:1080/foo
content-type: application/json

{
  "data": {
    "type": "JSON",
    "meta": {}
  }
}

###
POST http://localhost:1080/foo
content-type: application/xml

<data>
  <type>JSON</type>
  <meta>
    <bar>bar-val</bar>
    <baz>
      <qux>69</qux>
      <qux>96</qux>
    </baz>
  </meta>
</data>

###
POST http://localhost:1080/foo
content-type: application/xml

<data>
  <type>XML</type>
  <meta>
    <bar>bar-val</bar>
    <baz>
      <qux>69</qux>
      <qux>96</qux>
    </baz>
  </meta>
</data>

###
DELETE http://localhost:1080/foo/my.email@company.com/baz/wild card2